# Generated by Django 6.0.7 on 2026-08-17 12:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('content', models.TextField(help_text='One paragraph daily gratitude reflection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gratitude_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journal_entries',
                'ordering': ['-date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'date'), name='unique_owner_daily_entry')],
            },
        ),
    ]
